services:
  - type: web
    name: gateway
    runtime: docker
    rootDir: backend-java/gateway
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/gateway-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  - type: web
    name: postings
    runtime: docker
    rootDir: backend-java/postings
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/postings-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  - type: web
    name: dealer
    runtime: docker
    rootDir: backend-java/dealer
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/dealer-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  - type: web
    name: technician
    runtime: docker
    rootDir: backend-java/techincian
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/techincian-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  - type: web
    name: tech-dashboard
    runtime: docker
    rootDir: backend-java/tech-dashboard
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/tech-dashboard-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  - type: web
    name: chat-service
    runtime: node
    rootDir: backend-node/chat-service
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: postgres
          property: host
      - key: DB_USER
        fromDatabase:
          name: postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: DB_NAME
        value: inspection
      - key: DB_PORT
        value: 5432

  - type: web
    name: dealer-frontend
    runtime: static
    rootDir: frontend/dealer-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build

databases:
  - name: postgres
    plan: free
