import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import api, { API_CONFIG } from "../api";
import SearchableLocationDropdown from "./SearchableLocationDropdown";
import "bootstrap/dist/css/bootstrap.min.css";

function DealerRegister() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
    location: "",
    zipcode: "",
    phone: "",
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      // dealerId removed - auto-generated by backend
      const requestData = {
        ...formData,
      };

      // Use API_CONFIG for gateway access
      const fullUrl = `${API_CONFIG.DEALER_BASE_URL}/register`;
      console.log("API_CONFIG.DEALER_BASE_URL:", API_CONFIG.DEALER_BASE_URL);
      console.log("Using gateway URL:", fullUrl);
      console.log("Dealer Register - Request data:", requestData);

      const response = await axios.post(fullUrl, requestData, {
        headers: {
          "Content-Type": "application/json",
        },
      });

      console.log("Dealer Register - Response:", response.data);

      if (response.data && response.data.success) {
        console.log("Dealer Register - Success, navigating to login");
        navigate("/dealer-login", {
          state: { message: "Registration successful! Please login." },
        });
      } else {
        setError(response.data?.message || "Registration failed");
      }
    } catch (err) {
      console.error("Dealer Register - Error:", err);
      if (err.response?.status === 400) {
        // Try to get specific error message from backend
        const errorMsg = err.response?.data?.message || 
                        err.response?.data?.error || 
                        "Invalid data. Please check all fields.";
        setError(errorMsg);
      } else if (err.response?.status === 409) {
        setError("Email or Dealer ID already exists");
      } else {
        setError("Registration failed. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="min-vh-100 d-flex align-items-center justify-content-center px-3 py-4"
      style={{
        background:
          "linear-gradient(135deg, #e0f7fa 0%, #f3e5f5 50%, #fffde7 100%)",
        fontFamily: "'Poppins', sans-serif",
      }}
    >
      <div
        className="card shadow-lg border-0"
        style={{
          maxWidth: "600px",
          width: "100%",
          borderRadius: "20px",
          background: "rgba(255, 255, 255, 0.95)",
          backdropFilter: "blur(20px)",
        }}
      >
        <div
          className="card-header text-center text-white"
          style={{
            background: "linear-gradient(90deg, #0d6efd 0%, #6610f2 100%)",
            borderTopLeftRadius: "20px",
            borderTopRightRadius: "20px",
            padding: "2rem",
          }}
        >
          <h3 className="mb-0 fw-bold">👤 Dealer Registration</h3>
          <p className="mb-0 mt-2" style={{ opacity: 0.9 }}>
            Create your dealer account
          </p>
        </div>

        <div className="card-body p-4">
          {error && (
            <div className="alert alert-danger" role="alert">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit}>
            <div className="row">
              {/* Dealer ID removed - auto-generated by backend */}

              <div className="col-md-6 mb-3">
                <label htmlFor="name" className="form-label fw-semibold">
                  Dealer Name <span className="text-danger">*</span>
                </label>
                <input
                  type="text"
                  className="form-control"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  required
                  minLength="2"
                  maxLength="100"
                  placeholder="Enter dealer name"
                  autoComplete="name"
                  style={{
                    borderRadius: "10px",
                    border: "2px solid #e3e6ea",
                    padding: "10px 14px",
                  }}
                />
              </div>
            </div>

            <div className="mb-3">
              <label htmlFor="email" className="form-label fw-semibold">
                Email Address <span className="text-danger">*</span>
              </label>
              <input
                type="email"
                className="form-control"
                id="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                required
                placeholder="Enter your email"
                autoComplete="email"
                style={{
                  borderRadius: "10px",
                  border: "2px solid #e3e6ea",
                  padding: "10px 14px",
                }}
              />
            </div>

            <div className="mb-3">
              <label htmlFor="password" className="form-label fw-semibold">
                Password <span className="text-danger">*</span>
              </label>
              <input
                type="password"
                className="form-control"
                id="password"
                name="password"
                value={formData.password}
                onChange={handleChange}
                required
                minLength="8"
                placeholder="Enter password (min 8 characters)"
                autoComplete="new-password"
                style={{
                  borderRadius: "10px",
                  border: "2px solid #e3e6ea",
                  padding: "10px 14px",
                }}
              />
            </div>

            <div className="row">
              <div className="col-md-8 mb-3">
                <label htmlFor="location" className="form-label fw-semibold">
                  Location <span className="text-danger">*</span>
                </label>
                <SearchableLocationDropdown
                  id="location"
                  name="location"
                  value={formData.location}
                  onChange={handleChange}
                  placeholder="Search for your city..."
                  required
                />
              </div>

              <div className="col-md-4 mb-3">
                <label htmlFor="zipcode" className="form-label fw-semibold">
                  Zipcode <span className="text-danger">*</span>
                </label>
                <input
                  type="text"
                  className="form-control"
                  id="zipcode"
                  name="zipcode"
                  value={formData.zipcode}
                  onChange={handleChange}
                  required
                  minLength="5"
                  maxLength="10"
                  placeholder="Zipcode"
                  autoComplete="postal-code"
                  style={{
                    borderRadius: "10px",
                    border: "2px solid #e3e6ea",
                    padding: "10px 14px",
                  }}
                />
              </div>
            </div>

            <div className="mb-4">
              <label htmlFor="phone" className="form-label fw-semibold">
                Phone Number <span className="text-danger">*</span>
              </label>
              <input
                type="tel"
                className="form-control"
                id="phone"
                name="phone"
                value={formData.phone}
                onChange={handleChange}
                required
                pattern="^[\+]?[1-9]?[0-9]{7,15}$"
                placeholder="Enter phone number"
                autoComplete="tel"
                style={{
                  borderRadius: "10px",
                  border: "2px solid #e3e6ea",
                  padding: "10px 14px",
                }}
              />
              <small className="text-muted">
                Format: +1234567890 or 1234567890
              </small>
            </div>

            <button
              type="submit"
              className="btn btn-primary btn-lg w-100 fw-bold"
              disabled={loading}
              style={{
                borderRadius: "12px",
                background: "linear-gradient(90deg, #0d6efd 0%, #6610f2 100%)",
                border: "none",
                padding: "14px",
              }}
            >
              {loading ? (
                <>
                  <span className="spinner-border spinner-border-sm me-2" />
                  Creating Account...
                </>
              ) : (
                "Create Dealer Account"
              )}
            </button>
          </form>

          <div className="text-center mt-4">
            <p className="text-muted">
              Already have an account?{" "}
              <button
                className="btn btn-link p-0 fw-semibold"
                onClick={() => navigate("/dealer-login")}
              >
                Login here
              </button>
            </p>
            <button
              className="btn btn-outline-secondary mt-2"
              onClick={() => navigate("/")}
            >
              ← Back to Home
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DealerRegister;
